# Generated by Django 2.2.4 on 2019-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
