# Generated by Django 2.2.4 on 2019-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botusers', '0003_remove_botuser_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
