# Generated by Django 2.2.4 on 2019-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botusers', '0004_botuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='username'),
        ),
    ]
