# Generated by Django 2.2.4 on 2019-08-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botusers', '0005_auto_20190827_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
    ]
